name: Agrinho_Arapa_Tiangua
description: Programa Agrinho Município de Tiangua-CE.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  flutter_inappwebview: ^6.1.4
  flutter_launcher_icons: ^0.14.4
  convex_bottom_bar: ^3.2.0
  #assets_audio_player: ^3.0.8
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/inicial/
    - assets/saudavel/
    - assets/icons/
    - assets/songs/
    - assets/frecheirinha/




flutter_launcher_icons:
  android: true
  image_path: "Users/Administrator/ProjetosProgramacao/agrinho_tiangua/assets/icons/icon.png"
  min_sdk_android: 27 # android min sdk min:16, default 21


